.TH "Account.h" 3 "Fri Jun 26 2020" "Version 1.0.0.3" "SIP Phone" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Account.h
.SH SYNOPSIS
.br
.PP
\fC#include <Windows\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include <sys/timeb\&.h>\fP
.br
\fC#include <tchar\&.h>\fP
.br
\fC#include <process\&.h>\fP
.br
\fC#include <delayimp\&.h>\fP
.br
\fC#include <stdlib\&.H>\fP
.br
\fC#include <signal\&.h>\fP
.br
\fC#include <memory>\fP
.br
\fC#include <array>\fP
.br
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <mutex>\fP
.br
\fC#include <pjsua2\&.hpp>\fP
.br
\fC#include 'Call\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMyAccount\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SIP Phone from the source code\&.
