.TH "CMediaStream.h" 3 "Fri Jun 26 2020" "Version 1.0.0.3" "SIP Phone" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMediaStream.h
.SH SYNOPSIS
.br
.PP
\fC#include <pjlib\&.h>\fP
.br
\fC#include <pjlib\-util\&.h>\fP
.br
\fC#include <pjnath\&.h>\fP
.br
\fC#include <pjsip\&.h>\fP
.br
\fC#include <pjsip_ua\&.h>\fP
.br
\fC#include <pjsip_simple\&.h>\fP
.br
\fC#include <pjsua\-lib/pjsua\&.h>\fP
.br
\fC#include <pjmedia\&.h>\fP
.br
\fC#include <pjmedia\-codec\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCMediaStream\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef unsigned short \fBin_port_t\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef unsigned short \fBin_port_t\fP"

.PP
Definition at line 13 of file CMediaStream\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for SIP Phone from the source code\&.
