.TH "CMediaStream" 3 "Fri Jun 26 2020" "Version 1.0.0.3" "SIP Phone" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CMediaStream
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CMediaStream\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCMediaStream\fP ()"
.br
.ti -1c
.RI "\fB~CMediaStream\fP ()"
.br
.ti -1c
.RI "bool \fB_Init\fP ()"
.br
.ti -1c
.RI "void \fB_Test\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file CMediaStream\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CMediaStream::CMediaStream ()"

.SS "CMediaStream::~CMediaStream ()"

.SH "Member Function Documentation"
.PP 
.SS "bool CMediaStream::_Init ()"

.SS "void CMediaStream::_Test ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for SIP Phone from the source code\&.
