.TH "MyCall" 3 "Fri Jun 26 2020" "Version 1.0.0.3" "SIP Phone" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MyCall
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Call\&.h>\fP
.PP
Inherits Call\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMyCall\fP (Account &acc, int call_id=PJSUA_INVALID_ID)"
.br
.ti -1c
.RI "virtual \fB~MyCall\fP ()"
.br
.ti -1c
.RI "void \fB_Microfon\fP (DWORD dwLevel)"
.br
.ti -1c
.RI "void \fB_Sound\fP (DWORD dwLevel)"
.br
.ti -1c
.RI "bool \fB_Disconnect\fP ()"
.br
.ti -1c
.RI "virtual void \fBonCallState\fP (OnCallStateParam &prm) final"
.br
.ti -1c
.RI "virtual void \fBonCallMediaState\fP (OnCallMediaStateParam &prm) final"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 21 of file Call\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MyCall::MyCall (Account & acc, int call_id = \fCPJSUA_INVALID_ID\fP)"

.PP
Definition at line 6 of file Call\&.cpp\&.
.SS "MyCall::~MyCall ()\fC [virtual]\fP"

.PP
Definition at line 11 of file Call\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "bool MyCall::_Disconnect ()"

.PP
Definition at line 44 of file Call\&.cpp\&.
.SS "void MyCall::_Microfon (DWORD dwLevel)"

.PP
Definition at line 16 of file Call\&.cpp\&.
.SS "void MyCall::_Sound (DWORD dwLevel)"

.PP
Definition at line 30 of file Call\&.cpp\&.
.SS "void MyCall::onCallMediaState (OnCallMediaStateParam & prm)\fC [final]\fP, \fC [virtual]\fP"

.PP
Definition at line 151 of file Call\&.cpp\&.
.SS "void MyCall::onCallState (OnCallStateParam & prm)\fC [final]\fP, \fC [virtual]\fP"

.PP
Definition at line 96 of file Call\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SIP Phone from the source code\&.
