.TH "nsMsg::SIncCall" 3 "Fri Jun 26 2020" "Version 1.0.0.3" "SIP Phone" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nsMsg::SIncCall
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CSIPProcess\&.h>\fP
.PP
Inherits \fBnsMsg::SMsg\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "wstring \fBwstrCallingPNum\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 51 of file CSIPProcess\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "wstring nsMsg::SIncCall::wstrCallingPNum"
код сообщения 
.PP
Definition at line 53 of file CSIPProcess\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SIP Phone from the source code\&.
