.TH "nsMsg::SDisconnect" 3 "Fri Jun 26 2020" "Version 1.0.0.3" "SIP Phone" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nsMsg::SDisconnect
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CSIPProcess\&.h>\fP
.PP
Inherits \fBnsMsg::SMsg\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "wstring \fBwstrInfo\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 64 of file CSIPProcess\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "wstring nsMsg::SDisconnect::wstrInfo"
строка для записи в лог файл 
.PP
Definition at line 66 of file CSIPProcess\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SIP Phone from the source code\&.
